/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.com.cybertech.audio;

public class EchoCanceller {
  public static void start(int audio_track_min_buf_size, int audio_record_min_buf_size, int playback_delay_ms, int echo_delay_ms, int _dump_raw, int is_aec_available) {
    EchoCancellerJNI.start(audio_track_min_buf_size, audio_record_min_buf_size, playback_delay_ms, echo_delay_ms, _dump_raw, is_aec_available);
  }

  public static void runNearendProcessing() {
    EchoCancellerJNI.runNearendProcessing();
  }

  public static void stop() {
    EchoCancellerJNI.stop();
  }

  public static int push(short[] buf) {
    return EchoCancellerJNI.push(buf);
  }

  public static int pull(short[] buf) {
    return EchoCancellerJNI.pull(buf);
  }

  public static int estimate_delay(int use_mem_data) {
    return EchoCancellerJNI.estimate_delay(use_mem_data);
  }

  public static int get_estimated_echo_delay() {
    return EchoCancellerJNI.get_estimated_echo_delay();
  }

  public static void offline_process() {
    EchoCancellerJNI.offline_process();
  }

}
