/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensl_example;

public class opensl_example {
  public static void init() {
    opensl_exampleJNI.init();
  }

  public static void run() {
    opensl_exampleJNI.run();
  }

  public static void close() {
    opensl_exampleJNI.close();
  }

  public static int push(short[] buf) {
    return opensl_exampleJNI.push(buf);
  }

  public static int pull(short[] buf) {
    return opensl_exampleJNI.pull(buf);
  }

  public static void speex_ec_open(int sampleRate, int bufsize, int totalSize) {
    opensl_exampleJNI.speex_ec_open(sampleRate, bufsize, totalSize);
  }

  public static void speex_ec_process(SWIGTYPE_p_short input_frame, SWIGTYPE_p_short echo_frame, int len, SWIGTYPE_p_short output_frame) {
    opensl_exampleJNI.speex_ec_process(SWIGTYPE_p_short.getCPtr(input_frame), SWIGTYPE_p_short.getCPtr(echo_frame), len, SWIGTYPE_p_short.getCPtr(output_frame));
  }

  public static void speex_ec_close() {
    opensl_exampleJNI.speex_ec_close();
  }

  public static double getTimestamp() {
    return opensl_exampleJNI.getTimestamp();
  }

}
