/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensl_example;

public class opensl_example {
  public static void init() {
    opensl_exampleJNI.init();
  }

  public static void run() {
    opensl_exampleJNI.run();
  }

  public static void close() {
    opensl_exampleJNI.close();
  }

  public static int push(short[] buf) {
    return opensl_exampleJNI.push(buf);
  }

  public static int pull(short[] buf) {
    return opensl_exampleJNI.pull(buf);
  }

  public static double getTimestamp() {
    return opensl_exampleJNI.getTimestamp();
  }

}
