/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensl_example;

public class opensl_example {
  public static void start(int audio_track_min_buf_size, int audio_record_min_buf_size, int playback_delay_ms) {
    opensl_exampleJNI.start(audio_track_min_buf_size, audio_record_min_buf_size, playback_delay_ms);
  }

  public static void runNearendProcessing() {
    opensl_exampleJNI.runNearendProcessing();
  }

  public static void stop() {
    opensl_exampleJNI.stop();
  }

  public static int push(short[] buf) {
    return opensl_exampleJNI.push(buf);
  }

  public static int pull(short[] buf) {
    return opensl_exampleJNI.pull(buf);
  }

<<<<<<< HEAD
  public static int estimate_delay(int async) {
    return opensl_exampleJNI.estimate_delay(async);
=======
  public static SWIGTYPE_p_void estimate_delay(int async) {
    long cPtr = opensl_exampleJNI.estimate_delay(async);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
>>>>>>> d8e73d5d31568343fa35a384ce002334007dfb38
  }

  public static double getTimestamp() {
    return opensl_exampleJNI.getTimestamp();
  }

}
